/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import Modelo.BC;
import Modelo.Coche;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author Guillermo
 * 
 * 
 * SSMS 2017 Acceder desde Java
 * 
 */
public class InterfazUsuario extends javax.swing.JFrame {

    protected static final String PRIORIDAD_1 = "Minimizar precio";
    protected static final String PRIORIDAD_2 = "Maximizar comodidad";
    protected static final String PRIORIDAD_3 = "Minimizar coste viaje";

    BC bd = new BC() ;
    ArrayList<String> Lista = new ArrayList<String>();
    ArrayList<String> listaPrioridad = new ArrayList<String>();

    boolean primera = true;
    boolean segunda = true;
    boolean segundof = true;
    boolean primera1 = true;
    boolean comenzar = true;
    boolean filtro = true;
    boolean limpiado = false;
    String marchaTipo = "";

    /**
     * Creates new form NewJFrame
     */
    public InterfazUsuario() throws IOException {
        initComponents();
        Limpiar.setEnabled(false);
        Calcular.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        marcha = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        primerFiltro = new javax.swing.JComboBox<>();
        Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        Prioridad1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Comenzar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text3 = new javax.swing.JTextPane();

        marcha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        marcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marchaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        primerFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        primerFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerFiltroActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("TipoCoche");

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        Prioridad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Prioridad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prioridad1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Prioridades");

        Comenzar.setText("Comenzar");
        Comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(text3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primerFiltro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1))
                            .addComponent(Prioridad1, 0, 286, Short.MAX_VALUE))
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(primerFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Prioridad1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primerFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerFiltroActionPerformed

        if (comenzar) {
            return;
        } else {
            primerFiltro.setEnabled(false);
            segunda = false;
            Prioridad1.setEnabled(true);
        }
    }//GEN-LAST:event_primerFiltroActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        limpiarCelda();

    }//GEN-LAST:event_LimpiarActionPerformed

    private void marchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marchaActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        if (filtro) return;        
        if (!limpiado) return;
        
//        calcularPrecio(String[] prioridad, String tipo,
                //String marcha, String combustible){

//        bd.calcularPrecio(listaPrioridad, (String) primerFiltro.getSelectedItem(),
//            marchaTipo);
        text3.setText(bd.calcularPrecio((String) primerFiltro.getSelectedItem(),(String) Prioridad1.getSelectedItem()));
       // bd.calcularPrecio((String) Prioridad1.getSelectedItem(), (String) primerFiltro.getSelectedItem());
        /*
            Aqui va la accion del boton para que muestre por TextPrecio el precio
            final.
        
   (String tipo, String modelo, String marca, String marcha, String combustible)
         */

    }//GEN-LAST:event_CalcularActionPerformed

    private void Prioridad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prioridad1ActionPerformed
        if (comenzar) {
            return;
        }
        if (!limpiado) {
            return;
        } else {
            Lista.remove(Prioridad1.getSelectedItem());
            listaPrioridad.add((String) Prioridad1.getSelectedItem());
            Prioridad1.setEnabled(false);
            filtro = false;
            
            Calcular.setEnabled(true);

        }
    }//GEN-LAST:event_Prioridad1ActionPerformed

    private void ComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarActionPerformed

        iniciar();
        comenzar = false;
        Limpiar.setEnabled(true);
        Calcular.setEnabled(false);
        Comenzar.setEnabled(false);
    }//GEN-LAST:event_ComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazUsuario().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    private void iniciar() {
        limpiarCelda();
    }

    private void limpiarCelda() {
        limpiado = false;
        bd.iniciarListas();
        restablecerBoolean();
        limparCeldaRemoverElementos();
        rellenarBotonCoche(primerFiltro, bd.devuelveTipo());
        limpiarCeldaBoton();//Todos los botones iniciados correctamente
        nuevaListaPrioridad();
        text3.setText("");
        limpiado = true;

    }

    private void restablecerBoolean() {
        segunda = true;
        segundof = true;
        filtro = true;
    }

    private void limparCeldaRemoverElementos() {
        listaPrioridad.clear();
        vaciarElementos(primerFiltro);
        vaciarElementos(Prioridad1);
    }

    private void rellenarBotonCoche(JComboBox box, List lista) {
        for (int i = 0; i < lista.size(); i++) {
            box.addItem((String) lista.get(i));
        }
    }

    private void nuevaListaPrioridad() {

        vaciarElementos(Prioridad1);
        nuevaLista(Lista);
        rellenarPrioridad(Prioridad1, Lista);
        Prioridad1.setEnabled(false);

    }

    private void vaciarElementos(JComboBox<String> e) {
        e.removeAllItems();
        e.removeAll();
    }

    private void rellenarPrioridad(JComboBox<String> e, ArrayList<String> lista) {
        for (int i = 0; i < lista.size(); i++) {
            e.addItem(lista.get(i));
        }
    }

    private void nuevaLista(ArrayList<String> l) {
        l.clear();
        l.add(PRIORIDAD_1);
        l.add(PRIORIDAD_2);
        l.add(PRIORIDAD_3);
    }

    private void limpiarCeldaBoton() {
        primerFiltro.setEnabled(true);
        Calcular.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JButton Comenzar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JComboBox<String> Prioridad1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> marcha;
    private javax.swing.JComboBox<String> primerFiltro;
    private javax.swing.JTextPane text3;
    // End of variables declaration//GEN-END:variables
}
